In [1]:
from ECOv002_calval_tables import load_calval_table
from PTJPLSM import generate_PTJPLSM_table_inputs

In [12]:
calval_df = load_calval_table()
calval_df["tower"] = calval_df["ID"]
calval_df["lat"] = calval_df["Lat"]
calval_df["lon"] = calval_df["Long"]
calval_df["elevation_km"] = calval_df["Elev"] / 1000
calval_df

,Unnamed: 0,ID,vegetation,climate,STICinst,BESSinst,MOD16inst,PTJPLSMinst,ETinst,ETinstUncertainty,...,Ta_C,SWin_Wm2,emissivity,insitu_Rn_daylight_Wm2,insitu_LE_daylight_Wm2,insitu_ET_daylight_kg,tower,lat,lon,elevation_km
0,0,US-NC3,ENF,Cfa,270.345200,78.53355,392.851840,307.021970,487.383423,118.916280,...,32.658920,545.51056,0.948,268.829847,205.089552,3.521847,US-NC3,35.7990,-76.6560,0.005
1,1,US-Mi3,CVM,Dfb,232.141600,229.20093,640.118470,375.089300,106.825577,167.919460,...,24.227982,848.34390,0.952,346.382557,152.046364,3.361398,US-Mi3,41.8222,-80.6370,0.270
2,2,US-Mi3,CVM,Dfb,356.355740,335.23154,625.661700,284.686250,NaN,132.936340,...,26.178862,838.81160,0.972,311.373843,181.941076,4.018909,US-Mi3,41.8222,-80.6370,0.270
3,3,US-Mi3,CVM,Dfb,332.938400,326.68680,624.254330,251.414490,178.827545,141.132420,...,22.527096,851.72480,0.974,298.014172,153.111127,3.377459,US-Mi3,41.8222,-80.6370,0.270
4,4,US-Mi3,CVM,Dfb,286.854030,237.21654,511.082180,228.520170,154.791626,114.809410,...,23.280691,702.55160,0.960,300.483101,114.280419,2.519399,US-Mi3,41.8222,-80.6370,0.270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1060,1060,US-xAE,GRA,Cfa,70.923310,172.37459,81.645230,15.282976,NaN,56.385185,...,3.815752,286.84660,0.980,130.709188,6.649726,0.094448,US-xAE,35.4106,-99.0588,0.516
1061,1061,US-xAE,GRA,Cfa,116.543190,121.81641,65.469320,22.186659,NaN,40.509410,...,19.266186,290.87400,0.976,189.792524,71.961900,1.284029,US-xAE,35.4106,-99.0588,0.516
1062,1062,US-xAE,GRA,Cfa,129.880100,0.00000,118.777240,55.343586,NaN,52.403820,...,32.110336,352.19530,0.976,151.583691,77.678077,1.461298,US-xAE,35.4106,-99.0588,0.516
1063,1063,US-xAE,GRA,Cfa,2.707851,140.38632,126.490524,40.434025,NaN,57.769722,...,10.464681,420.67880,0.976,291.834038,79.346005,1.500961,US-xAE,35.4106,-99.0588,0.516
1064,1064,US-xAE,GRA,Cfa,303.242950,0.00000,271.749480,119.763630,190.823303,122.092445,...,30.316103,781.84110,0.978,331.951225,95.853257,1.842696,US-xAE,35.4106,-99.0588,0.516

In [13]:
for item in sorted(calval_df.columns):
    print(item)

AirTempC
BESSinst
Clim
Date-Time
ESI
ESIrn_BESS
ESIrn_LEcorr50
ESIrn_MOD16
ESIrn_PTJPLSM
ESIrn_STIC
ESIrn_Unc_ECO
ETinst
ETinstUncertainty
Elev
EmisWB
EndDate
G_filt
H_filt
Hcorr25
Hcorr50
Hcorr75
Hcorr_ann
ID
JET
LE
LE_count
LE_filt
LEcorr25
LEcorr50
LEcorr75
LEcorr_ann
LST
LST_err
Lat
Long
MAP
MAT
MOD16inst
NDVI
NDVI-UQ
NETRAD_filt
Name
PET
PTJPLSMinst
RH
RH_percentage
Rg
Rn
SM
SM_rz
SM_surf
STICinst
ST_C
ST_K
SW_IN
SWin_Wm2
Site ID
Site Name
StartDate
Ta
Ta_C
Unnamed: 0
Veg
albedo
albedo-UQ
climate
closure_ratio
eco_time_utc
elevation_km
emissivity
geometry
insitu_ET_daylight_kg
insitu_LE_daylight_Wm2
insitu_Rn_daylight_Wm2
lat
local_time
lon
solar_hour
solar_time
time_UTC
time_utc
tower
vegetation
view_zenith

In [14]:
calval_df["Elev"]

0         5.0
1       270.0
2       270.0
3       270.0
4       270.0
        ...
1060    516.0
1061    516.0
1062    516.0
1063    516.0
1064    516.0
Name: Elev, Length: 1065, dtype: float64

In [15]:
inputs_df = generate_PTJPLSM_table_inputs(calval_df)
inputs_df

[2025-10-02 13:58:45 INFO] collecting PTJPL inputs for tower US-NC3 lat 35.799 lon -76.656 time 2019-10-02 19:09:40 UTC
[2025-10-02 13:58:46 INFO] generating Topt_C
Topt_C: 10.09
[2025-10-02 13:58:46 INFO] generating fAPARmax
fAPARmax: 0.46590000000000004
[2025-10-02 13:58:46 INFO] generating field_capacity
field_capacity: 0.24
[2025-10-02 13:58:46 INFO] generating wilting_point
wilting_point: 0.09
[2025-10-02 13:58:46 INFO] generating canopy_height_meters
canopy_height_meters: 21.369150712961353
[2025-10-02 13:58:46 INFO] collecting PTJPL inputs for tower US-Mi3 lat 41.8222 lon -80.637 time 2019-06-23 18:17:17 UTC
[2025-10-02 13:58:46 INFO] generating Topt_C
Topt_C: 1.3900000000000001
[2025-10-02 13:58:46 INFO] generating fAPARmax
fAPARmax: 0.48650000000000004
[2025-10-02 13:58:46 INFO] generating field_capacity
field_capacity: 0.32
[2025-10-02 13:58:46 INFO] generating wilting_point
wilting_point: 0.13
[2025-10-02 13:58:46 INFO] generating canopy_height_meters
canopy_height_meters: 0.0
[2025-10-02 13:58:46 INFO] collecting PTJPL inputs for tower US-Mi3 lat 41.8222 lon -80.637 time 2019-06-27 16:35:42 UTC
[2025-10-02 13:58:46 INFO] generating Topt_C
Topt_C: 1.3900000000000001
[2025-10-02 13:58:46 INFO] generating fAPARmax
fAPARmax: 0.48650000000000004
[2025-10-02 13:58:46 INFO] generating field_capacity
field_capacity: 0.32
[2025-10-02 13:58:46 INFO] generating wilting_point
wilting_point: 0.13
[2025-10-02 13:58:46 INFO] generating canopy_height_meters
canopy_height_meters: 0.0
[2025-10-02 13:58:46 INFO] collecting PTJPL inputs for tower US-Mi3 lat 41.8222 lon -80.637 time 2019-06-30 15:44:10 UTC
[2025-10-02 13:58:46 INFO] generating Topt_C
Topt_C: 1.3900000000000001
[2025-10-02 13:58:46 INFO] generating fAPARmax
fAPARmax: 0.48650000000000004
[2025-10-02 13:58:46 INFO] generating field_capacity
field_capacity: 0.32
[2025-10-02 13:58:46 INFO] generating wilting_point
wilting_point: 0.13
[2025-10-02 13:58:46 INFO] generating canopy_height_meters
canopy_height_meters: 0.0
[2025-10-02 13:58:46 INFO] collecting PTJPL inputs for tower US-Mi3 lat 41.8222 lon -80.637 time 2019-07-01 14:53:48 UTC
[2025-10-02 13:58:46 INFO] generating Topt_C
Topt_C: 1.3900000000000001
[2025-10-02 13:58:46 INFO] generating fAPARmax
fAPARmax: 0.48650000000000004
[2025-10-02 13:58:46 INFO] generating field_capacity
field_capacity: 0.32
[2025-10-02 13:58:46 INFO] generating wilting_point
wilting_point: 0.13
[2025-10-02 13:58:46 INFO] generating canopy_height_meters
canopy_height_meters: 0.0
[2025-10-02 13:58:46 INFO] collecting PTJPL inputs for tower US-Mi3 lat 41.8222 lon -80.637 time 2019-07-08 12:22:09 UTC
[2025-10-02 13:58:46 INFO] generating Topt_C
Topt_C: 1.3900000000000001
[2025-10-02 13:58:46 INFO] generating fAPARmax
fAPARmax: 0.48650000000000004
[2025-10-02 13:58:46 INFO] generating field_capacity
field_capacity: 0.32
[2025-10-02 13:58:46 INFO] generating wilting_point
wilting_point: 0.13
[2025-10-02 13:58:46 INFO] generating canopy_height_meters
canopy_height_meters: 0.0
[2025-10-02 13:58:46 INFO] collecting PTJPL inputs for tower US-NC4 lat 35.7879 lon -75.9038 time 2020-10-05 17:19:50 UTC
[2025-10-02 13:58:46 INFO] generating Topt_C
Topt_C: 9.74
[2025-10-02 13:58:46 INFO] generating fAPARmax
fAPARmax: 0.5777
[2025-10-02 13:58:46 INFO] generating field_capacity
field_capacity: 0.3
[2025-10-02 13:58:46 INFO] generating wilting_point
wilting_point: 0.13
[2025-10-02 13:58:46 INFO] generating canopy_height_meters
canopy_height_meters: 15.211540730086531
[2025-10-02 13:58:46 INFO] collecting PTJPL inputs for tower US-Mi1 lat 41.7727 lon -80.6313 time 2019-06-23 18:17:17 UTC
[2025-10-02 13:58:46 INFO] generating Topt_C
Topt_C: 2.06
[2025-10-02 13:58:46 INFO] generating fAPARmax
fAPARmax: 0.4792
[2025-10-02 13:58:46 INFO] generating field_capacity
field_capacity: 0.31
[2025-10-02 13:58:46 INFO] generating wilting_point
wilting_point: 0.14
[2025-10-02 13:58:46 INFO] generating canopy_height_meters
canopy_height_meters: 0.0
[2025-10-02 13:58:46 INFO] collecting PTJPL inputs for tower US-Mi1 lat 41.7727 lon -80.6313 time 2019-06-30 15:44:10 UTC
[2025-10-02 13:58:46 INFO] generating Topt_C
Topt_C: 2.06
[2025-10-02 13:58:46 INFO] generating fAPARmax
fAPARmax: 0.4792
[2025-10-02 13:58:46 INFO] generating field_capacity
field_capacity: 0.31
[2025-10-02 13:58:46 INFO] generating wilting_point
wilting_point: 0.14
[2025-10-02 13:58:46 INFO] generating canopy_height_meters
canopy_height_meters: 0.0
[2025-10-02 13:58:46 INFO] collecting PTJPL inputs for tower US-Mi1 lat 41.7727 lon -80.6313 time 2019-07-01 14:53:48 UTC
[2025-10-02 13:58:46 INFO] generating Topt_C
Topt_C: 2.06
[2025-10-02 13:58:46 INFO] generating fAPARmax
fAPARmax: 0.4792
[2025-10-02 13:58:46 INFO] generating field_capacity
field_capacity: 0.31
[2025-10-02 13:58:46 INFO] generating wilting_point
wilting_point: 0.14
[2025-10-02 13:58:46 INFO] generating canopy_height_meters
canopy_height_meters: 0.0
[2025-10-02 13:58:46 INFO] collecting PTJPL inputs for tower US-Mi1 lat 41.7727 lon -80.6313 time 2019-07-08 12:22:09 UTC
[2025-10-02 13:58:46 INFO] generating Topt_C
Topt_C: 2.06
[2025-10-02 13:58:46 INFO] generating fAPARmax
fAPARmax: 0.4792
[2025-10-02 13:58:46 INFO] generating field_capacity
field_capacity: 0.31
[2025-10-02 13:58:47 INFO] generating wilting_point
wilting_point: 0.14
[2025-10-02 13:58:47 INFO] generating canopy_height_meters
canopy_height_meters: 0.0
[2025-10-02 13:58:47 INFO] collecting PTJPL inputs for tower US-Mi1 lat 41.7727 lon -80.6313 time 2019-08-25 17:08:28 UTC
[2025-10-02 13:58:47 INFO] generating Topt_C
Topt_C: 2.06
[2025-10-02 13:58:47 INFO] generating fAPARmax
fAPARmax: 0.4792
[2025-10-02 13:58:47 INFO] generating field_capacity
field_capacity: 0.31
[2025-10-02 13:58:47 INFO] generating wilting_point
wilting_point: 0.14
[2025-10-02 13:58:47 INFO] generating canopy_height_meters
canopy_height_meters: 0.0
[2025-10-02 13:58:47 INFO] collecting PTJPL inputs for tower US-PFe lat 45.9793 lon -90.3004 time 2019-10-09 18:18:59 UTC
[2025-10-02 13:58:47 INFO] generating Topt_C
Topt_C: 0.0
[2025-10-02 13:58:47 INFO] generating fAPARmax
fAPARmax: 0.47390000000000004
[2025-10-02 13:58:47 INFO] generating field_capacity
field_capacity: 0.28
[2025-10-02 13:58:47 INFO] generating wilting_point
wilting_point: 0.1
[2025-10-02 13:58:47 INFO] generating canopy_height_meters
canopy_height_meters: 11.71780221418252
[2025-10-02 13:58:47 INFO] collecting PTJPL inputs for tower US-xAB lat 45.7624 lon -122.3303 time 2021-04-06 20:52:18 UTC
[2025-10-02 13:58:47 INFO] generating Topt_C
Topt_C: 6.69
[2025-10-02 13:58:47 INFO] generating fAPARmax
fAPARmax: 0.604
[2025-10-02 13:58:47 INFO] generating field_capacity
field_capacity: 0.34
[2025-10-02 13:58:47 INFO] generating wilting_point
wilting_point: 0.16
[2025-10-02 13:58:47 INFO] generating canopy_height_meters
canopy_height_meters: 12.43357166311379
[2025-10-02 13:58:47 INFO] collecting PTJPL inputs for tower US-xAB lat 45.7624 lon -122.3303 time 2021-04-13 18:34:21 UTC
[2025-10-02 13:58:47 INFO] generating Topt_C
Topt_C: 6.69
[2025-10-02 13:58:47 INFO] generating fAPARmax
fAPARmax: 0.604
[2025-10-02 13:58:47 INFO] generating field_capacity
field_capacity: 0.34
[2025-10-02 13:58:47 INFO] generating wilting_point
wilting_point: 0.16
[2025-10-02 13:58:47 INFO] generating canopy_height_meters
canopy_height_meters: 12.43357166311379
[2025-10-02 13:58:47 INFO] collecting PTJPL inputs for tower US-xAB lat 45.7624 lon -122.3303 time 2021-04-17 17:01:32 UTC
[2025-10-02 13:58:47 INFO] generating Topt_C
Topt_C: 6.69
[2025-10-02 13:58:47 INFO] generating fAPARmax
fAPARmax: 0.604
[2025-10-02 13:58:47 INFO] generating field_capacity
field_capacity: 0.34
[2025-10-02 13:58:47 INFO] generating wilting_point
wilting_point: 0.16
[2025-10-02 13:58:47 INFO] generating canopy_height_meters
canopy_height_meters: 12.43357166311379
[2025-10-02 13:58:47 INFO] collecting PTJPL inputs for tower US-xAB lat 45.7624 lon -122.3303 time 2021-04-17 21:53:48 UTC
[2025-10-02 13:58:47 INFO] generating Topt_C
Topt_C: 6.69
[2025-10-02 13:58:47 INFO] generating fAPARmax
fAPARmax: 0.604
[2025-10-02 13:58:47 INFO] generating field_capacity
field_capacity: 0.34
[2025-10-02 13:58:47 INFO] generating wilting_point
wilting_point: 0.16
[2025-10-02 13:58:47 INFO] generating canopy_height_meters
canopy_height_meters: 12.43357166311379
[2025-10-02 13:58:47 INFO] collecting PTJPL inputs for tower US-xAB lat 45.7624 lon -122.3303 time 2021-04-18 16:14:45 UTC
[2025-10-02 13:58:47 INFO] generating Topt_C
Topt_C: 6.69
[2025-10-02 13:58:47 INFO] generating fAPARmax
fAPARmax: 0.604
[2025-10-02 13:58:47 INFO] generating field_capacity
field_capacity: 0.34
[2025-10-02 13:58:47 INFO] generating wilting_point
wilting_point: 0.16
[2025-10-02 13:58:47 INFO] generating canopy_height_meters
canopy_height_meters: 12.43357166311379
[2025-10-02 13:58:47 INFO] collecting PTJPL inputs for tower US-xAB lat 45.7624 lon -122.3303 time 2021-06-16 21:54:08 UTC
[2025-10-02 13:58:47 INFO] generating Topt_C
Topt_C: 6.69
[2025-10-02 13:58:47 INFO] generating fAPARmax
fAPARmax: 0.604
[2025-10-02 13:58:47 INFO] generating field_capacity
field_capacity: 0.34
[2025-10-02 13:58:47 INFO] generating wilting_point
wilting_point: 0.16
[2025-10-02 13:58:47 INFO] generating canopy_height_meters
canopy_height_meters: 12.43357166311379
[2025-10-02 13:58:47 INFO] collecting PTJPL inputs for tower US-xAB lat 45.7624 lon -122.3303 time 2021-06-20 20:21:02 UTC
[2025-10-02 13:58:47 INFO] generating Topt_C
Topt_C: 6.69
[2025-10-02 13:58:47 INFO] generating fAPARmax
fAPARmax: 0.604
[2025-10-02 13:58:47 INFO] generating field_capacity
field_capacity: 0.34
[2025-10-02 13:58:47 INFO] generating wilting_point
wilting_point: 0.16
[2025-10-02 13:58:47 INFO] generating canopy_height_meters
canopy_height_meters: 12.43357166311379
[2025-10-02 13:58:47 INFO] collecting PTJPL inputs for tower US-xAB lat 45.7624 lon -122.3303 time 2021-06-23 14:43:40 UTC
[2025-10-02 13:58:47 INFO] generating Topt_C
Topt_C: 6.69
[2025-10-02 13:58:47 INFO] generating fAPARmax
fAPARmax: 0.604
[2025-10-02 13:58:47 INFO] generating field_capacity
field_capacity: 0.34
[2025-10-02 13:58:47 INFO] generating wilting_point
wilting_point: 0.16
[2025-10-02 13:58:47 INFO] generating canopy_height_meters
canopy_height_meters: 12.43357166311379
[2025-10-02 13:58:47 INFO] collecting PTJPL inputs for tower US-xAB lat 45.7624 lon -122.3303 time 2021-06-25 18:00:37 UTC
[2025-10-02 13:58:47 INFO] generating Topt_C
Topt_C: 6.69
[2025-10-02 13:58:47 INFO] generating fAPARmax
fAPARmax: 0.604
[2025-10-02 13:58:47 INFO] generating field_capacity
field_capacity: 0.34
[2025-10-02 13:58:47 INFO] generating wilting_point
wilting_point: 0.16
[2025-10-02 13:58:47 INFO] generating canopy_height_meters
canopy_height_meters: 12.43357166311379
[2025-10-02 13:58:47 INFO] collecting PTJPL inputs for tower US-xAB lat 45.7624 lon -122.3303 time 2021-07-26 01:38:51 UTC
[2025-10-02 13:58:47 INFO] generating Topt_C
Topt_C: 6.69
[2025-10-02 13:58:47 INFO] generating fAPARmax
fAPARmax: 0.604
[2025-10-02 13:58:47 INFO] generating field_capacity
field_capacity: 0.34
[2025-10-02 13:58:47 INFO] generating wilting_point
wilting_point: 0.16
[2025-10-02 13:58:47 INFO] generating canopy_height_meters
canopy_height_meters: 12.43357166311379
[2025-10-02 13:58:47 INFO] collecting PTJPL inputs for tower US-xAB lat 45.7624 lon -122.3303 time 2021-08-11 18:42:06 UTC
[2025-10-02 13:58:47 INFO] generating Topt_C
Topt_C: 6.69
[2025-10-02 13:58:47 INFO] generating fAPARmax
fAPARmax: 0.604
[2025-10-02 13:58:47 INFO] generating field_capacity
field_capacity: 0.34
[2025-10-02 13:58:47 INFO] generating wilting_point
wilting_point: 0.16
[2025-10-02 13:58:47 INFO] generating canopy_height_meters
canopy_height_meters: 12.43357166311379
[2025-10-02 13:58:47 INFO] collecting PTJPL inputs for tower US-xAB lat 45.7624 lon -122.3303 time 2021-08-15 17:09:33 UTC
[2025-10-02 13:58:47 INFO] generating Topt_C
Topt_C: 6.69
[2025-10-02 13:58:47 INFO] generating fAPARmax
fAPARmax: 0.604
[2025-10-02 13:58:47 INFO] generating field_capacity
field_capacity: 0.34
[2025-10-02 13:58:47 INFO] generating wilting_point
wilting_point: 0.16
[2025-10-02 13:58:47 INFO] generating canopy_height_meters
canopy_height_meters: 12.43357166311379
[2025-10-02 13:58:47 INFO] collecting PTJPL inputs for tower US-xAB lat 45.7624 lon -122.3303 time 2022-06-27 17:08:07 UTC
[2025-10-02 13:58:47 INFO] generating Topt_C
Topt_C: 6.69
[2025-10-02 13:58:47 INFO] generating fAPARmax
fAPARmax: 0.604
[2025-10-02 13:58:47 INFO] generating field_capacity
field_capacity: 0.34
[2025-10-02 13:58:47 INFO] generating wilting_point
wilting_point: 0.16
[2025-10-02 13:58:47 INFO] generating canopy_height_meters
canopy_height_meters: 12.43357166311379
[2025-10-02 13:58:48 INFO] collecting PTJPL inputs for tower US-xAB lat 45.7624 lon -122.3303 time 2022-07-27 01:01:57 UTC
[2025-10-02 13:58:48 INFO] generating Topt_C
Topt_C: 6.69
[2025-10-02 13:58:48 INFO] generating fAPARmax
fAPARmax: 0.604
[2025-10-02 13:58:48 INFO] generating field_capacity
field_capacity: 0.34
[2025-10-02 13:58:48 INFO] generating wilting_point
wilting_point: 0.16
[2025-10-02 13:58:48 INFO] generating canopy_height_meters
canopy_height_meters: 12.43357166311379
[2025-10-02 13:58:48 INFO] collecting PTJPL inputs for tower US-xAB lat 45.7624 lon -122.3303 time 2022-07-28 00:13:06 UTC
[2025-10-02 13:58:48 INFO] generating Topt_C
Topt_C: 6.69
[2025-10-02 13:58:48 INFO] generating fAPARmax
fAPARmax: 0.604
[2025-10-02 13:58:48 INFO] generating field_capacity
field_capacity: 0.34
[2025-10-02 13:58:48 INFO] generating wilting_point
wilting_point: 0.16
[2025-10-02 13:58:48 INFO] generating canopy_height_meters
canopy_height_meters: 12.43357166311379
[2025-10-02 13:58:48 INFO] collecting PTJPL inputs for tower US-xAB lat 45.7624 lon -122.3303 time 2022-08-03 21:47:00 UTC
[2025-10-02 13:58:48 INFO] generating Topt_C
Topt_C: 6.69
[2025-10-02 13:58:48 INFO] generating fAPARmax
fAPARmax: 0.604
[2025-10-02 13:58:48 INFO] generating field_capacity
field_capacity: 0.34
[2025-10-02 13:58:48 INFO] generating wilting_point
wilting_point: 0.16
[2025-10-02 13:58:48 INFO] generating canopy_height_meters
canopy_height_meters: 12.43357166311379
[2025-10-02 13:58:48 INFO] collecting PTJPL inputs for tower US-xAB lat 45.7624 lon -122.3303 time 2022-08-07 20:09:16 UTC
[2025-10-02 13:58:48 INFO] generating Topt_C
Topt_C: 6.69
[2025-10-02 13:58:48 INFO] generating fAPARmax
fAPARmax: 0.604
[2025-10-02 13:58:48 INFO] generating field_capacity
field_capacity: 0.34
[2025-10-02 13:58:48 INFO] generating wilting_point
wilting_point: 0.16
[2025-10-02 13:58:48 INFO] generating canopy_height_meters
canopy_height_meters: 12.43357166311379
[2025-10-02 13:58:48 INFO] collecting PTJPL inputs for tower US-HBK lat 43.9397 lon -71.7181 time 2019-08-02 19:50:07 UTC
[2025-10-02 13:58:48 WARNING] polygon for target 19TBJ not found
[2025-10-02 13:58:48 INFO] collecting PTJPL inputs for tower US-HBK lat 43.9397 lon -71.7181 time 2019-08-06 18:09:26 UTC
[2025-10-02 13:58:48 WARNING] polygon for target 19TBJ not found
[2025-10-02 13:58:48 INFO] collecting PTJPL inputs for tower US-HBK lat 43.9397 lon -71.7181 time 2019-10-05 18:22:24 UTC
[2025-10-02 13:58:48 WARNING] polygon for target 19TBJ not found
[2025-10-02 13:58:48 INFO] collecting PTJPL inputs for tower US-HBK lat 43.9397 lon -71.7181 time 2021-06-10 15:27:35 UTC
[2025-10-02 13:58:48 WARNING] polygon for target 19TBJ not found
[2025-10-02 13:58:48 INFO] collecting PTJPL inputs for tower US-HBK lat 43.9397 lon -71.7181 time 2021-06-24 15:42:38 UTC
[2025-10-02 13:58:48 WARNING] polygon for target 19TBJ not found
[2025-10-02 13:58:48 INFO] collecting PTJPL inputs for tower US-HBK lat 43.9397 lon -71.7181 time 2021-08-27 14:20:12 UTC
[2025-10-02 13:58:48 WARNING] polygon for target 19TBJ not found
[2025-10-02 13:58:48 INFO] collecting PTJPL inputs for tower US-HBK lat 43.9397 lon -71.7181 time 2022-05-01 12:28:11 UTC
[2025-10-02 13:58:48 WARNING] polygon for target 19TBJ not found
[2025-10-02 13:58:48 INFO] collecting PTJPL inputs for tower US-Me6 lat 44.3233 lon -121.6078 time 2019-06-04 22:32:36 UTC
[2025-10-02 13:58:48 INFO] generating Topt_C
Topt_C: 0.0
[2025-10-02 13:58:48 INFO] generating fAPARmax
fAPARmax: 0.48510000000000003
[2025-10-02 13:58:48 INFO] generating field_capacity
field_capacity: 0.28
[2025-10-02 13:58:48 INFO] generating wilting_point
wilting_point: 0.11
[2025-10-02 13:58:48 INFO] generating canopy_height_meters
canopy_height_meters: 9.958437111815588
[2025-10-02 13:58:48 INFO] collecting PTJPL inputs for tower US-Me6 lat 44.3233 lon -121.6078 time 2019-06-14 23:59:11 UTC
[2025-10-02 13:58:48 INFO] generating Topt_C
Topt_C: 0.0
[2025-10-02 13:58:48 INFO] generating fAPARmax
fAPARmax: 0.48510000000000003
[2025-10-02 13:58:48 INFO] generating field_capacity
field_capacity: 0.28
[2025-10-02 13:58:48 INFO] generating wilting_point
wilting_point: 0.11
[2025-10-02 13:58:48 INFO] generating canopy_height_meters
canopy_height_meters: 9.958437111815588
[2025-10-02 13:58:48 INFO] collecting PTJPL inputs for tower US-Me6 lat 44.3233 lon -121.6078 time 2019-06-15 18:17:56 UTC
[2025-10-02 13:58:48 INFO] generating Topt_C
Topt_C: 0.0
[2025-10-02 13:58:48 INFO] generating fAPARmax
fAPARmax: 0.48510000000000003
[2025-10-02 13:58:48 INFO] generating field_capacity
field_capacity: 0.28
[2025-10-02 13:58:48 INFO] generating wilting_point
wilting_point: 0.11
[2025-10-02 13:58:48 INFO] generating canopy_height_meters
canopy_height_meters: 9.958437111815588
[2025-10-02 13:58:48 INFO] collecting PTJPL inputs for tower US-Me6 lat 44.3233 lon -121.6078 time 2019-06-17 23:07:28 UTC
[2025-10-02 13:58:48 INFO] generating Topt_C
Topt_C: 0.0
[2025-10-02 13:58:48 INFO] generating fAPARmax
fAPARmax: 0.48510000000000003
[2025-10-02 13:58:48 INFO] generating field_capacity
field_capacity: 0.28
[2025-10-02 13:58:48 INFO] generating wilting_point
wilting_point: 0.11
[2025-10-02 13:58:48 INFO] generating canopy_height_meters
canopy_height_meters: 9.958437111815588
[2025-10-02 13:58:48 INFO] collecting PTJPL inputs for tower US-Me6 lat 44.3233 lon -121.6078 time 2019-06-18 17:25:55 UTC
[2025-10-02 13:58:48 INFO] generating Topt_C
Topt_C: 0.0
[2025-10-02 13:58:48 INFO] generating fAPARmax
fAPARmax: 0.48510000000000003
[2025-10-02 13:58:48 INFO] generating field_capacity
field_capacity: 0.28
[2025-10-02 13:58:48 INFO] generating wilting_point
wilting_point: 0.11
[2025-10-02 13:58:48 INFO] generating canopy_height_meters
canopy_height_meters: 9.958437111815588
[2025-10-02 13:58:48 INFO] collecting PTJPL inputs for tower US-Me6 lat 44.3233 lon -121.6078 time 2019-06-19 16:36:33 UTC
[2025-10-02 13:58:48 INFO] generating Topt_C
Topt_C: 0.0
[2025-10-02 13:58:48 INFO] generating fAPARmax
fAPARmax: 0.48510000000000003
[2025-10-02 13:58:48 INFO] generating field_capacity
field_capacity: 0.28
[2025-10-02 13:58:48 INFO] generating wilting_point
wilting_point: 0.11
[2025-10-02 13:58:48 INFO] generating canopy_height_meters
canopy_height_meters: 9.958437111815588
[2025-10-02 13:58:48 INFO] collecting PTJPL inputs for tower US-Me6 lat 44.3233 lon -121.6078 time 2019-07-06 15:30:41 UTC
[2025-10-02 13:58:48 INFO] generating Topt_C
Topt_C: 0.0
[2025-10-02 13:58:48 INFO] generating fAPARmax
fAPARmax: 0.48510000000000003
[2025-10-02 13:58:48 INFO] generating field_capacity
field_capacity: 0.28
[2025-10-02 13:58:48 INFO] generating wilting_point
wilting_point: 0.11
[2025-10-02 13:58:48 INFO] generating canopy_height_meters
canopy_height_meters: 9.958437111815588
[2025-10-02 13:58:48 INFO] collecting PTJPL inputs for tower US-Me6 lat 44.3233 lon -121.6078 time 2019-07-29 01:24:40 UTC
[2025-10-02 13:58:48 INFO] generating Topt_C
Topt_C: 0.0
[2025-10-02 13:58:48 INFO] generating fAPARmax
fAPARmax: 0.48510000000000003
[2025-10-02 13:58:48 INFO] generating field_capacity
field_capacity: 0.28
[2025-10-02 13:58:48 INFO] generating wilting_point
wilting_point: 0.11
[2025-10-02 13:58:48 INFO] generating canopy_height_meters

,Unnamed: 0,ID,vegetation,climate,STICinst,BESSinst,MOD16inst,PTJPLSMinst,ETinst,ETinstUncertainty,...,lat,lon,elevation_km,hour_of_day,doy,Topt_C,fAPARmax,field_capacity,wilting_point,canopy_height_meters
0,0,US-NC3,ENF,Cfa,270.345200,78.53355,392.851840,307.021970,487.383423,118.916280,...,35.7990,-76.6560,0.005,14,275,10.09,0.4659,0.24,0.09,21.369151
1,1,US-Mi3,CVM,Dfb,232.141600,229.20093,640.118470,375.089300,106.825577,167.919460,...,41.8222,-80.6370,0.270,12,174,1.39,0.4865,0.32,0.13,0.000000
2,2,US-Mi3,CVM,Dfb,356.355740,335.23154,625.661700,284.686250,NaN,132.936340,...,41.8222,-80.6370,0.270,11,178,1.39,0.4865,0.32,0.13,0.000000
3,3,US-Mi3,CVM,Dfb,332.938400,326.68680,624.254330,251.414490,178.827545,141.132420,...,41.8222,-80.6370,0.270,10,181,1.39,0.4865,0.32,0.13,0.000000
4,4,US-Mi3,CVM,Dfb,286.854030,237.21654,511.082180,228.520170,154.791626,114.809410,...,41.8222,-80.6370,0.270,9,182,1.39,0.4865,0.32,0.13,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1060,1060,US-xAE,GRA,Cfa,70.923310,172.37459,81.645230,15.282976,NaN,56.385185,...,35.4106,-99.0588,0.516,9,345,7.99,0.3387,0.28,0.13,0.000000
1061,1061,US-xAE,GRA,Cfa,116.543190,121.81641,65.469320,22.186659,NaN,40.509410,...,35.4106,-99.0588,0.516,16,84,7.99,0.3387,0.28,0.13,0.000000
1062,1062,US-xAE,GRA,Cfa,129.880100,0.00000,118.777240,55.343586,NaN,52.403820,...,35.4106,-99.0588,0.516,16,102,7.99,0.3387,0.28,0.13,0.000000
1063,1063,US-xAE,GRA,Cfa,2.707851,140.38632,126.490524,40.434025,NaN,57.769722,...,35.4106,-99.0588,0.516,8,104,7.99,0.3387,0.28,0.13,0.000000
1064,1064,US-xAE,GRA,Cfa,303.242950,0.00000,271.749480,119.763630,190.823303,122.092445,...,35.4106,-99.0588,0.516,13,110,7.99,0.3387,0.28,0.13,0.000000